# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'techStack' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for techStack

  target 'techStack-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'techStackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'techStack-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for techStack-tvOS

  #target 'techStack-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

#end
